# Generated by Django 3.1.5 on 2021-01-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210105_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-created_at',), 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
